apiVersion: apps/v1
kind: Deployment
metadata:
  name: horamundial
  labels:
    app: horamundial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: horamundial
  template:
    metadata:
      labels:
        app: horamundial
    spec:
      containers:
      - name: horamundial
        image: mnustes/horamundial:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10