apiVersion: v1
kind: Service
metadata:
  name: horamundial
  labels:
    app: horamundial
spec:
  type: LoadBalancer
  selector:
    app: horamundial
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080