replicaCount: 1
image:
  repository: mnustes/horamundial
  pullPolicy: IfNotPresent
  tag: "4e78e6979ac99dc6a7a1d9d2a294f7cf7714d5b7"
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
