replicaCount: 3
image:
  repository: mnustes/horamundial
  pullPolicy: IfNotPresent
  tag: "07af2f0e604df28fbf5c58e0738c1bb9a63276a9"
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
