replicaCount: 1
image:
  repository: mnustes/horamundial
  pullPolicy: IfNotPresent
  tag: "19f8f5261a55962c8eca846161b3aeaee723045a"
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
