replicaCount: 1
image:
  repository: mnustes/horamundial
  pullPolicy: IfNotPresent
  tag: "6d3cbadae809f54746c4a7e29220b8523aa9c2bd"
service:
  type: LoadBalancer
  port: 80
  targetPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
